### ISSUE TITLE
Installation failure on macos

### ISSUE THREAD

**Issue by Tridacnid** [KonstantinKai/proto-flutter-plugin#2]
I'm giving proto a try and saw that there was a flutter plugin, which is great!

Running the snippet off https://moonrepo.dev/docs/proto/tools#third-party results in 
```
% proto plugin add flutter "github://KonstantinKai/proto-flutter-plugin"                                          

│ SUCCESS
│ Added flutter plugin to config <dir redacted>

% proto install flutter 
──────────────────── Downloading pre-built archive flutter_macos_arm64_3.32.0-stable.zip | Error: proto::checksum::unknown_algorithm

  × Unknown checksum algorithm. Unable to derive from ~/.proto/temp/flutter/3.32.0/
  │ CHECKSUM.
  help: Try using a more explicit file extension.
```

as seen above, I'm using macos, specifically sequoia 15.4.1
```
% proto --version
proto 0.49.3
```

**Comment by ganobrega** [comment]
Hey!

I made an alternative using TOML.

```toml
name = "flutter"
type = "cli"

[platform.linux]
archive-prefix = "flutter"
download-file = "flutter_linux_{arch}{version}-stable.tar.xz"

[platform.macos]
archive-prefix = "flutter"
download-file = "flutter_macos_{arch}{version}-stable.zip"

[platform.windows]
archive-prefix = "flutter"
download-file = "flutter_windows_{arch}{version}-stable.exe"

[install]
download-url = "https://storage.googleapis.com/flutter_infra_release/releases/stable/{os}/{download_file}"

[install.primary]
exe-path = "bin/flutter"

[install.secondary.dart]
exe-path = "bin/dart"

[install.secondary.flutter-dev]
exe-path = "bin/flutter-dev"

[install.arch]
aarch64 = "_arm64_"
x86_64 = ""

[resolve]
git-url = "https://github.com/flutter/flutter"
```

You can try editing the `nano ~/.prototools`

And adding the file locally:

```toml
[plugins]
flutter = "file:///home/gabriel/Github/ganobrega/proto-flutter-plugin/plugin.toml"
```

Or

```bash
$ proto plugin add flutter "https://raw.githubusercontent.com/ganobrega/proto-flutter-plugin/refs/heads/main/plugin.toml"
$ proto install flutter
```
